### PR TITLE
Update conanfile.py

### PR DESCRIPTION
**Pull request by bredej**
Deleted variable self.options.shared throws an exception when accessed in configure(self)

### CODE REVIEW

**Comment by memsharded** [comment]
Hi @bredej 

I think your fix make sense, thanks for submitting it. I guess that you found it while trying to use ``tbbproxy`` option.

Would like the feedback of @SSE4 , main contributor of this recipe.

**Comment by SSE4** [comment]
@uilianries 
we have currently 3 ways to address this:
- remove shared option
- raise ConanInvalidConfiguration for `shared=False` on Windows
- silently fallback to `shared=True` as PR suggests
what do you think, which approach is the best one?

**Comment by uilianries** [comment]
I prefer to expose only what the user can do, in this case, it will not be able to manipulate `shared`, so why should we expose it as an option?

I would prefer removing `shared` when building on Windows, and update build.py
You could use libelf as example: [conanfile.py](https://github.com/bincrafters/conan-libelf/blob/b85e577cb204a7cc25600c5dddf7ebce62cdfb26/conanfile.py#L30) and [build.py](https://github.com/bincrafters/conan-libelf/blob/b85e577cb204a7cc25600c5dddf7ebce62cdfb26/build.py#L11)

**Comment by SSE4** [comment]
okay, let's change the failing condition then

**Pull request merged**
